### ISSUE TITLE
Supplementary Material?

### ISSUE THREAD

**Issue by LuoweiZhou** [shyamal-b/sst#1]
Hi Shyamal, will the supplementary material be available soon? I noticed some hyper-params (e.g., k) are not specified in the full paper. Also, how about the source code? Thank you!

**Comment by shyamal-b** [comment]
Hi @LuoweiZhou - Yes, definitely. The SM should be up sometime in the next couple of weeks before the conference. Juggling a couple of deadlines right now - thanks for your patience! 😄 

(Closing issue for now, but will update this thread once the commits are in :) )
