### ISSUE TITLE
where is the supplementary material?

### ISSUE THREAD

**Issue by RyanCV** [shyamal-b/sst#2]
Hi, as mentioned in your paper u will release the supplementary material in this website, could u tell me where is it? Thx.

**Comment by shyamal-b** [comment]
Hi @RyanCV - the supplementary material will be released here very soon (within the next few weeks, prior to the upcoming conference in late July). Thank you for your patience! 😄

**Comment by happygds** [comment]
@shyamal-b Would it be released in these two days ?

**Comment by shyamal-b** [comment]
@happygds that's the plan! (Although we may release additional stuff in the days after)

**Comment by happygds** [comment]
@shyamal-b hi, would the generated proposals on THUMOS-14 be also released ?

**Comment by shyamal-b** [comment]
Forgot to close this issue earlier! For anyone looking back on this, all the above material has been up for a little while.
