### ISSUE TITLE
can not download  the pre-trained model ？ 

### ISSUE THREAD

**Issue by gooners1886** [shyamal-b/sst#4]
can not download the model from 
 https://dl.dropboxusercontent.com/s/81hlnp2g7p5gqpq/sst_demo_th14_k32.hkl  

the log is ：
$wget https://dl.dropboxusercontent.com/s/81hlnp2g7p5gqpq/sst_demo_th14_k32.hkl
--2017-10-11 23:12:16--  https://dl.dropboxusercontent.com/s/81hlnp2g7p5gqpq/sst_demo_th14_k32.hkl
Resolving dl.dropboxusercontent.com... 93.46.8.89
Connecting to dl.dropboxusercontent.com|93.46.8.89|:443... failed: Connection timed out.
Retrying.

--2017-10-11 23:13:22--  (try: 2)  https://dl.dropboxusercontent.com/s/81hlnp2g7p5gqpq/sst_demo_th14_k32.hkl
Connecting to dl.dropboxusercontent.com|93.46.8.89|:443... failed: Connection timed out.
Retrying.

is the link avaliabe ？

**Comment by shyamal-b** [comment]
Hi @gooners1886 - the link _should_ still be working fine. What country are you downloading from? Dropbox also rate-limits downloadable links to a particular number of download attempts per day - maybe try again now?

**Comment by gooners1886** [comment]
@shyamal-b  I try again and get a file about 2.4 MB, is the file that small? 
can you provide the md5 value of that file so i can check if i have downloaded the whole file successfully ? 
my value is below: 
md5sum sst_demo_th14_k32.hkl 
93928147c0cc2bb2a70b39295d1c5c75  sst_demo_th14_k32.hkl

is the file OK ?

**Comment by shyamal-b** [comment]
Yes, that looks correct:

```
MD5 (sst_demo_th14_k32.hkl) = 93928147c0cc2bb2a70b39295d1c5c75
```

**Comment by gooners1886** [comment]
@shyamal-b  thank you very much!!
