### ISSUE TITLE
What's the 'th14_filter.csv'?

### ISSUE THREAD

**Issue by dhlee-jubilee** [shyamal-b/sst#5]
Thanks for good research!
(1) I'm wondering some part in 'generate_sst_props.py'

def parse_args():
...
p.add_argument('-ff', '--filter-file', help='filter file for dataset.',
                   default='th14_filter.csv', type=str)

What is the 'th14_filter.csv'? 

(2) 'stride' variable is not declared in 'sst/utils.py'

Best,

dongheon Lee

**Comment by shyamal-b** [comment]
Hi @dhlee-jubilee,
(1) `th14_filter.csv` is an input file with the list of the video_ids in the dataset that you want to run on. We include this as part of the demo script as way you can select multiple input videos/whatever subset you want to evaluate. It is an optional argument, and if you don't provide it then it just runs the code on the full dataset. (for details, you can see [these lines in the code](https://github.com/shyamal-b/sst/blob/17ba3ccf290e4e872ada26cc3ee8be5baf4692c4/code/generate_sst_props.py#L60-L64))
(2) Good catch - thanks! `stride` is the same as `delta`, and the code has now been updated accordingly.

**Comment by dhlee-jubilee** [comment]
Thank you for your quick response.

Can I few more question?
I'd like to try train THUMOS14 video datasets as you did.
But I'm embarrassed that the video input type is not .avi or .mp4 but .hdf5 format.
I'm not familiar with .hdf5 format, so requesting you some converting tip.

Besides, I downloaded THUMOS15 video 'Test Data(untrimmed)' as your journal. 
Sadly, to unzip the data, it is required password, but the THUMOS Challenge 2014 is closed a few years ago. So, if you know I request the password as well!  Thanks.

Best,

dongheon Lee
